# Generated by Django 3.1.4 on 2021-07-05 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_code_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='name',
            field=models.URLField(max_length=100),
        ),
    ]
