# Generated by Django 3.1.4 on 2021-07-05 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_auto_20210705_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='url',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
