# Generated by Django 3.1.4 on 2021-07-05 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_auto_20210705_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='code',
            name='url',
            field=models.URLField(blank=True, max_length=100),
        ),
    ]
